### ISSUE TITLE
Still cannot generate binary?

### ISSUE THREAD

**Issue by qindj** [weyrick/roadsend-php-raven#4]
hi, admin

I just install the great project , when i try to use rphp -f test.php , but nothing happened, no output

I saw a sentence in README : PLEASE NOTE that code generation is currently disabled while we finish rewriting the front end. Try rphp-analyzer instead!

So it's cannot generate complied code now?

thank you

**Comment by weyrick** [comment]
This version (raven) of rphp does not generate binaries, that is correct. You can use the original version to generate binaries, though: https://github.com/weyrick/roadsend-php
